export const CONNECT_API = 'CONNECT_API'
export const FETCH_PROFIL = 'FETCH_PROFIL'
export const USER_LOGIN = 'USER_LOGIN'
export const CLICK_BUTTON = 'CLICK_BUTTON'
export const UPDATE_NAME = 'UPDATE_NAME'
export const LOGIN_OUT = 'LOGIN_OUT'
