swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profil/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction API
      description: Viewing transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/getTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          paths:
  /user/profil/transaction/details:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction API
      description: Viewing transactions details
      parameters:
        - in: header
          type: array
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction detail retrieved successully
          schema:
            $ref: '#/definitions/getTransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: User transaction API
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/getTransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/getTransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  getTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: string
            description: amount ($)
          balance:
            type: string
            description: balance ($)
  getTransactionsDetails:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          transactionType:
            type: string
            description: type of transaction
          category:
            type: string
            description: category of the transaction
          notes:
            type: string
            description: Notes from the user
